### ISSUE TITLE
Debugger breakpoints not working

### ISSUE THREAD

**Issue by jk779** [tomblachut/svelte-intellij#242]
Hi, i'm trying to use the Webstorm debugger for svelte files written in Typescript. I've followed [this article](https://www.jetbrains.com/help/webstorm/running-and-debugging-typescript.html#ws_ts_debug) on how to use the debugger when using an external application server (I'm using webpack/yarn).

Debugging works great and as expected within Webstorm when using the `debugger` keyword inside the TS code or when using sveltes `{@debug something}`. 

Sadly I'm not able to make the debugger pause execution when using Webstorms breakpoints. I've tried to use the "Ensure breakpoints are detected" option in the Javascript Debug configuration, but thats not working either.

Can you hint me to a direction where the problem could be? I've seen the svelte plugin [added support for debugging](https://github.com/tomblachut/svelte-intellij/issues/174), so I think I'm doing something wrong. Or is it expected that debugging works with the keywords debugger and @debug only?

**Comment by jiby-gh** [comment]
@tomblachut I just also noticed that this is not working. However i have seen it earlier working, could it be that this is also broken by the newer Webstorm build ?

**Comment by jiby-gh** [comment]
well, it was an issue with source map generation in my project, unrelated to the plugin. I Fixed the source map generation and breakpoints work just fine. So can ignore my last comment @tomblachut

**Comment by tomblachut** [comment]
@jiby-gh I appreciate your clarification, thanks.

**Comment by AnthoniG** [comment]
@tomblachut I seem to be having the same problem.
Followed the link jiby-gh  put and set up chrome for debugging.
I then put a breakpoint in the script tag and then ran the debugger.
It did not stop on the break point.

What am I doing wrong?
I am just using basic SvelteKit install npm init svelte@next demo (used Typescript as language).

Any help is appreciated.

**Comment by cristianvogel** [comment]
Hi. I am running into this issue. I have no breakpoints at all when in Run Dev, not for methods, components or html - I'd like to follow the link in this thread, but i don't see one.

**Comment by DanMossa** [comment]
I'm still unable to have my breakpoints work. I'm using Typescript if that matters.

**Comment by tomblachut** [comment]
Hi @DanMossa, looks like everyone else found a solution in the linked article. Please create an issue in WebStorm ZenDesk or [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WEB), that way our support engineers will be able to help you better
